### obtener todos los alumnos
GET  http://localhost:3000/api/alumnos

### obtener un alumno

GET http://localhost:3000/api/alumnos/3638

### crear un nuevo alumno

POST http://localhost:3000/api/alumnos
Content-Type: application/json


{
  "name": "Raul",
   "lastname": "Bruno",
   "age": 21,
    "email":"raulbruno@gmail.com"
}

### modificar un alumno (PUT - recurso completo e idempotente)

PUT http://localhost:3000/api/alumnos/7558
Content-Type: application/json

{
  "name": "Alejandro",
   "lastname": "Martorell",
   "age": 29,
    "email":"alemartore@gmail.com",
    "legajo":"10"
    }

### modificar un alumno (PATCH - recurso parcial)

PATCH http://localhost:3000/api/alumnos/5144
Content-Type: application/json

{
  "name": "Puma",
   "lastname": "Martorell",
      "email":"alemartorell.gg.ez@gmail.com"
}

### eliminar un alumno
DELETE  http://localhost:3000/api/alumnos/985